### ISSUE TITLE
Discord Bots offline / not responding to commands. 

### ISSUE THREAD

**Issue by Magicanz** [cameroncros/OctoPrint-DiscordRemote#107]
I've got 5 printers connected to one octopi, 3 of them have got cameras. The bots for those three often do not work. At a few times they start working one by one but quickly stop once again. The log files keep complaining about discordapp 502 bad gateway. I've attached the octopi log file. I'm not very skilled in programming, is this something I can fix or is it a discord problem. Is there a way to automatically restart the bot after these errors? Thanks!

[octoprint (1).log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/3653088/octoprint.1.log)

**Comment by cameroncros** [comment]
This is a very interesting failure, i have no idea what could be causing it.

**Comment by cameroncros** [comment]
@Magicanz, could you give me some more information about how you setup your 5 servers on 1 pi? I'm very curious to know how to do it so I can try replicate the issue.

On review of the code, I have noticed some minor issues that may be causing your problem, I will fix and push them in the coming days

**Comment by Magicanz** [comment]
@cameroncros It was some while ago now I set the Pi up, but this was the guide I used: http://thomas-messmer.com/index.php/14-free-knowledge/howtos/79-setting-up-octoprint-for-multiple-printers. I started out with three cameraless printers, put cameras on them within a month, then installed 2 new printers a couple months later.

**Comment by cameroncros** [comment]
Please upgrade to 2.51, and see if your problem still exists.

**Comment by cameroncros** [comment]
And if you can give any more log files, that would be greatly appreciated.

**Comment by Magicanz** [comment]
Problem seems to be fixed! Have only tried for about an hour though. Do you still want logs? (Sorry for late reply)

**Comment by cameroncros** [comment]
If anything goes wrong, reopen and add logs, otherwise I'm glad it's fixed :)
