### ISSUE TITLE
wrong webcam being displayed 

### ISSUE THREAD

**Issue by fatmann66** [cameroncros/OctoPrint-DiscordRemote#108]
I did see the comment about a "multicam plugin"   but I'm not  using it.

how is the plugin selecting the webcam? I would think it uses what's defined in octoprint config, but I have multiple instances running.

1st instance is working correctly.
2nd instance is pulling  cam feed for 3rd instance
so does it just pick the first seen webcam?? or is it pulling the cam from some setting in octoprint or your plugin itself? ca we specify a USB ID or serial to force it to the correct cam?

thanks,

**Comment by cameroncros** [comment]
@fatmann66 It is basically pulling the camera settings from octoprint. No idea how it is getting them confused. Is this a new issue for you, did an older version work correctly?
