### ISSUE TITLE
/outputstatus seems to be broken?

### ISSUE THREAD

**Issue by dsdanielko** [cameroncros/OctoPrint-DiscordRemote#109]
The discord bot does not respond with anything, otherwise, /outputon and /outputoff works perfectly.

**Comment by cameroncros** [comment]
Could you attach your log messages? I'll look into this soonish

**Comment by dsdanielko** [comment]
how do i see the log sorry

**Comment by cameroncros** [comment]
https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299

**Comment by dsdanielko** [comment]
There is nothing in the plugin_discordremote.log for either /outputon or /outputstatus but there is an error in octoprint.log around the times when I tried /outputstatus

> 2019-10-24 11:57:53,732 - websocket - ERROR - error from callback <bound method Discord.on_message of <octoprint_discordremote.discord.Discord instance at 0x75cc1df0>>: object of type 'bool' has no len()

[plugin_discordremote.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/3767149/plugin_discordremote.log)
