### ISSUE TITLE
Feature Request: Change Frequency in Discord?

### ISSUE THREAD

**Issue by techheaddj** [cameroncros/OctoPrint-DiscordRemote#111]
Would it be possible to have a /settings tag that would allow us to change the frequency from Discord for when we are using this to remotely monitor prints? For example, I am using this while I'm at work. With a 6h print going, I don't need an update every 10m like I would for a shorter 1-2hr print when I'm at home and just like it checking in.

**Comment by cameroncros** [comment]
Interesting idea, not a bad idea. I can't promise I will get around to this, but if you want to make this change I would be happy to merge it.
