### ISSUE TITLE
[Feature Request/Modification] Timelapse Numbered Gets

### ISSUE THREAD

**Issue by ciordia9** [cameroncros/OctoPrint-DiscordRemote#112]
Discord on mobile does not allow you to select text (or at least easily.) So it's nearly impossible to grab my timelapses with a name like CCCCFP_11315151912_2020010817542.mp4.

Can the timelapse list get turned into a numbered list where we can just /gettimelapse 1 or 2 or 3 or 4, etc etc?

Thank you!

**Comment by cameroncros** [comment]
Thanks for your suggestion. This would definitely be a nice thing to do, however, I don't have much time to dedicate to working on Discord remote at the moment, so I won't be able to do it any time soon. If you are able, you are welcome to make the change yourself and then create a pull request, I will happily review and merge it. I can answer any questions you have if you need help as well.
