### ISSUE TITLE
Ability to @ users and roles not working

### ISSUE THREAD

**Issue by IanJDan** [cameroncros/OctoPrint-DiscordRemote#117]
I've been trying to @ users and roles within the various configurable messages and it doesn't seem to work when entering any of the following values:
```
@UserName
@UserID
@UserNickname
@RoleName
@RoleID
```

I would really only expect the User/Role IDs above to work, but none work currently. I'd appreciate any assistance with this so I can alert a role when a job has completed.

**Comment by cameroncros** [comment]
See #83. Unless something has changed, I dont beleive that bots can @mention people in embeds. It might be possible with some effort though, as https://github.com/discordjs/discord.js/issues/1519 has a solution for discord.js. I am fairly busy with other tasks atm, so I dont want to work on this myself, but I am happy to assist you if you decide to try make the change yourself.

**Comment by wchill** [comment]
I have a solution, it's not the most pretty but I think it's an acceptable tradeoff. Basically you add it as the content parameter in the message send API call. I tried adding it as part of the embed description but unfortunately that didn't work to actually mention a user.

![image](https://user-images.githubusercontent.com/3746651/92083896-836de880-ed7b-11ea-8139-c98e6c161666.png)

I can clean this up and then send a PR when I have some time.

**Comment by cameroncros** [comment]
So basically, you want to send it as a plain message alongside the embed? I think thats a suitable compromise. Especially in conjunction with #129

**Comment by cameroncros** [comment]
Released in v2.57
