### ISSUE TITLE
Premission denied

### ISSUE THREAD

**Issue by thostie2002** [cameroncros/OctoPrint-DiscordRemote#123]
Hello how can i fix this?
Yes i have read the “manual” but cant find it 

![image](https://user-images.githubusercontent.com/48547379/82736400-dcb08f80-9d29-11ea-9189-56c6b119a895.jpeg)![image](https://user-images.githubusercontent.com/48547379/82736406-e0441680-9d29-11ea-99c9-b490ae8233a7.jpeg)

**Comment by cameroncros** [comment]
@thostie2002 The user ID needs to be the numerical form, which is a number like: 165259232034275409. The easiest way to get this, is to join a voice channel, and then right click your name, and click "Copy ID"

**Comment by thostie2002** [comment]
Great thanks man!!!  , now it works

**Comment by thostie2002** [comment]
Can you also give me a full list of commands that i can use?
