### ISSUE TITLE
Appears not to be working in latest Octoprint update ( OctoPrint 1.4.1, Python 2.7.16, OctoPi 0.17.0)

### ISSUE THREAD

**Issue by JamieS01** [cameroncros/OctoPrint-DiscordRemote#127]
![DiscordRemotePluginIssue](https://user-images.githubusercontent.com/60047145/89448553-b5c20100-d74f-11ea-8926-ab4e63df6d53.png)

I apologise if this is not the right place to post this, however I am not sure how to troubleshoot this problem and I use this plugin quite heavily so I would love to get it working again!

**Comment by cameroncros** [comment]
This is definitely the right place, but i am very confused about what is broken for you. I have updated my octoprint last night to 1.4.1, and its fine. Can you get me the logs from octoprint?

**Comment by JamieS01** [comment]
I'm really sorry, this is totally my mistake! When I was changing the permissions on my private server, I accidentally revoked the bot access to read messages and it totally broke it. Fixed now.
