### ISSUE TITLE
How can I @ users when a print job starts?

### ISSUE THREAD

**Issue by turtlenator0316** [cameroncros/OctoPrint-DiscordRemote#128]
![image](https://user-images.githubusercontent.com/69434620/89740178-86173f80-da54-11ea-99d5-0601812ad4ba.png)

I've tried multiple different ways of doing this, but can't get it to work

**Comment by cameroncros** [comment]
See #117. Unfortunately, it seems that it is not easy, if possible at all. If you have the ability, you are welcome to look into it and work out a solution.
