### ISSUE TITLE
Some sort of embed editor / way to make multi-line edits

### ISSUE THREAD

**Issue by Hexical1** [cameroncros/OctoPrint-DiscordRemote#129]
Hello! I really enjoy this plugin, but I think it would be amazing to be able to edit the actual embeds themselves. 

I did see an issue about this that is closed now, but as far as I can see I don't see any way in the UI to edit embeds - and I've dug around the config and don't have a clue where to start. I'd love to have my printing progress message look something like the one that pops up when I do /status.

Thanks for the amazing plugin though :)

**Comment by cameroncros** [comment]
That sounds like an awesome idea, but unless someone wants to work on it, i don't think it'll happen any time soon. Short term, the print message could be changed to be json or yaml, and use that to generate the embeds.

I do not have the time to work on this unfortunately, so I will not.

I will leave this ticket open so if someone has the time they can work on it.

**Comment by wchill** [comment]
I can take this when I have some time.

**Comment by cameroncros** [comment]
Released in v2.57

**Comment by cameroncros** [comment]
Reopening, so that a second attempt can be made at this.
