### ISSUE TITLE
[request} time format

### ISSUE THREAD

**Issue by jon012198** [cameroncros/OctoPrint-DiscordRemote#13]
time formatted in mins and hours  have no ideal what it is in like /status https://puu.sh/AE1Rn/ff2d678ae4.png

**Comment by cameroncros** [comment]
Fair request, its currently seconds, will format nicely

**Comment by cameroncros** [comment]
Have fixed this. Now has far more readable values for seconds. Might need some formatting in the future to make the table smaller and fit better into discord.

**Comment by jon012198** [comment]
and for the table you could use this https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/examples/using-embeds-in-messages.html

**Comment by cameroncros** [comment]
Gonna close this for now. Maybe later I will come back and make the tables nicer. Had a look at the embeds, dont see how a table fits in there, but might be useful.
