### ISSUE TITLE
Snapshots with Updates not showing

### ISSUE THREAD

**Issue by ccanevit** [cameroncros/OctoPrint-DiscordRemote#138]
With release 2.57.0, and continuing with the fix of 2.58.0, snapshots with updates are not occuring. Snapshot command does work, however periodic updates, and start of printing are not sending snapshots.
![image](https://user-images.githubusercontent.com/71088770/92757166-581e6700-f342-11ea-9c64-07a1378bed5c.png)
![image](https://user-images.githubusercontent.com/71088770/92757245-69677380-f342-11ea-829c-66e0b0eb37d1.png)
![image](https://user-images.githubusercontent.com/71088770/92757294-75533580-f342-11ea-9c41-86c4d10a8964.png)

**Comment by sg000** [comment]
I will concur with this issue. No snapshots with updates or conclusion with the latest release.

**Comment by wchill** [comment]
Have also noticed this and I think this is my bad. Will need to send out a bugfix.

**Comment by forouza1** [comment]
Same. Can concur no snapshots coming across but I see snapshots on /status commands.

**Comment by TGCFabian** [comment]
Think alot of people currently have the same problem, i thought i went crazy, adjusted all settings, reinstalled plugin several times, reflashed octoprint, just to find this lmao

**Comment by cameroncros** [comment]
@wchill I think i should have done a better review, there are a lot of breaking changes you accidentally made. I am gonna revert to v2.56.0, and start re-implementing the code in a cleaner way.

**Comment by TGCFabian** [comment]
Eventho of the breaks/bugs, i appriciate you guys working on the plugin :)
Sadly i dont have much discord python experience, otherwise i would have helped out :)

**Comment by cameroncros** [comment]
I've reverted the code from the past two releases, and it should be working now.

**Comment by ccanevit** [comment]
Thanks for working on this guys. I'll do my part and try to report legitimate issues for you.

**Comment by wchill** [comment]
Yeah @cameroncros I think I got confused by how your custom Discord implementation was doing some things.

**Comment by ccanevit** [comment]
I can confirm, after I uninstalled, and re-installed with the 2.59.0 version, that snapshots are now working.

**Comment by cameroncros** [comment]
@wchill yeah, it confuses me at the best of times as well. Really need to document it better.
