### ISSUE TITLE
[request] message test

### ISSUE THREAD

**Issue by jon012198** [cameroncros/OctoPrint-DiscordRemote#14]
a button to ping the discord bot so i dont have to remove one charter to reload the  bots connection

**Comment by jon012198** [comment]
Yup

**Comment by cameroncros** [comment]
I have added an indicator that shows the status of the discord bot. Still trying to work out the best way to send a test message from the web UI.

**Comment by cameroncros** [comment]
53382da7af005bf79e4dd081cd68932a65a627c3 Show status indicator in web interface
81fbd577504c709b648de21c2ac453662c115659 Send message from web interface (default status)

**Comment by jon012198** [comment]
formatting is off only when you use the button in octoprint but if you send a message in discord it is fine 
![discord_2018-06-19_08-37-55](https://user-images.githubusercontent.com/7279835/41597699-2ff7674a-739c-11e8-91d1-cfebfddc5072.png)
![discord_2018-06-19_08-38-11](https://user-images.githubusercontent.com/7279835/41597700-3008b9a0-739c-11e8-8524-afe69b022f83.png)

**Comment by cameroncros** [comment]
Whoops, only tested with status, and didnt look too carefully at alignment, will fix for next release.

**Comment by cameroncros** [comment]
Fixed the messages, and have made the tables a bit thinner, should print much nicer now.
