### ISSUE TITLE
Discord not Reporting Print Status

### ISSUE THREAD

**Issue by omac03** [cameroncros/OctoPrint-DiscordRemote#140]
Hello, I can connect to my Ender 3 pro running a SKR Mini E3 with the TFT35 Touchscreen using discord and get snapshots but when I poll status it says it is not printing when it is. Discord never report that the printer has started a job or is printing. I can connect and send commands over Discord so I am confused on what the issue can be. 
![Capture](https://user-images.githubusercontent.com/72173777/94755996-e98a6300-035b-11eb-862a-0cfbdc7b5e94.PNG)

**Comment by cameroncros** [comment]
I dont know what the problem is, do you have some logs? My plugin appears to work correctly for me.

**Comment by omac03** [comment]
Where do I pull the log from? I am not seeing one. In Octoprint terminal I get no status messages. I just updated the plugin but the discord still does not see it printing. What command is it looking for?

**Comment by omac03** [comment]
It is still not reporting the status of my prints. DO I need a certain gcode in my slicer? where do i pull the log from? The terminal log? Really need to get this resolved!

**Comment by cameroncros** [comment]
The logs are in the octoprints settings -> Logging -> octoprint_discordremote.log:
![image](https://user-images.githubusercontent.com/1438383/98443591-531e3e00-2160-11eb-9f89-c74a70664343.png)

**Comment by omac03** [comment]
Thank you! I have attached the log I have.
[plugin_discordremote.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/5504945/plugin_discordremote.log)

**Comment by omac03** [comment]
I resolved the issue. It seems that when printing through the TFT35 touch screen Octoprint does not report printing status. I went back to the internal SD card and it works perfectly now. Thanks!
