### ISSUE TITLE
[enhancement] mobile

### ISSUE THREAD

**Issue by jon012198** [cameroncros/OctoPrint-DiscordRemote#15]
formatting on mobile is bad  the status one is fine on mobile https://cdn.discordapp.com/attachments/423501252618485770/459528563129843722/image.png if you can get it to look like this it would be amazing https://puu.sh/AJHG3/17fbe588d6.png

**Comment by cameroncros** [comment]
But my beautiful ascii tables :(

In seriousness, probably would be good to get something more like that. Im not in a huge hurry to implement it though, so if you are about to do it, and it is something you want done, feel free to go for it. Otherwise I might get around to in in the future. If you want help with setting it up, let me know.

**Comment by cameroncros** [comment]
embeds have pretty bad limitations, as described by the link above. Not sure they are suitable. The markdown option may be worth exploring

**Comment by cameroncros** [comment]
markdown is pretty limited as well, might have to do more research

**Comment by cameroncros** [comment]
Markdown inside code blocks might be a way forward, I added the initial steps by adding a way to format the messages as markdown code blocks, will try add a table formatter that generates nice markdown tables, and see if that looks any nicer

**Comment by cameroncros** [comment]
I have created a embed based solution, but want to test it a bit more thoroughly. If your interested, install: https://github.com/cameroncros/OctoPrint-DiscordRemote/archive/DR-15.zip via the plugin manager.

**Comment by jon012198** [comment]
it looks good to me anything you want me to test  all of the commands work
right

**Comment by cameroncros** [comment]
If it is good for you, I will do a bit more cleanup and then release it for everyone
It is possible to send snapshots inside embeds, which i want to try as well, but might save that for later.

**Comment by cameroncros** [comment]
Added snapshots to the embeds. Will need to test with a real printer, but once that is done, I will merge and complete it. #31

**Comment by cameroncros** [comment]
Merged, if CI passes, will release
