### ISSUE TITLE
Commands for uploading files to discord are dumb.

### ISSUE THREAD

**Issue by Zinc-OS** [cameroncros/OctoPrint-DiscordRemote#153]
There should be a way to upload files to discord based on a number, say 1st in the list of gcodes, or 2nd, and the same for time lapses.

**Comment by Zinc-OS** [comment]
I'm going to work on this for my own use

**Comment by cameroncros** [comment]
To be honest, I thought that was already possible, but if you make that change, please create a PR back and I would be happy to merge it.
