### ISSUE TITLE
New octopi shows whether pi is throttled, /status should show this too.

### ISSUE THREAD

**Issue by Zinc-OS** [cameroncros/OctoPrint-DiscordRemote#156]
My pi is constantly getting throttled because I have it wired to my printer(which at best will give it what it needs) This should be simple so I will try and do this myself.

**Comment by cameroncros** [comment]
I actually have the exact same issue (pi claims to be throttled because its powered from the 5v always on rail of my printers PSU). This would be quite a useful feature I think. Please create a PR when you are ready, and I would be happy to merge it.
