### ISSUE TITLE
Printing progress messages not sending

### ISSUE THREAD

**Issue by InterstellarRobo** [cameroncros/OctoPrint-DiscordRemote#161]
I don't know what's up but neither of the printing progress messages are sending. All the other messages will send and they do correctly. Any idea what's happening?

**Comment by cameroncros** [comment]
Can you find the OctoPrint logs for Discord remote and upload them?

**Comment by InterstellarRobo** [comment]
[plugin_discordremote.log.2020-11-02.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/5504960/plugin_discordremote.log.2020-11-02.log)

Here they are. On Nov 1st was the day I set it up so if you see errors from then that's because I had no bot setup but I have that fixed now.

**Comment by cameroncros** [comment]
@InterstellarRobo Sorry for the delay.

At a quick skim, nothing looks out of place. What are you settings:
![image](https://user-images.githubusercontent.com/1438383/100494630-781e3380-3197-11eb-87b9-93cf6717d278.png)

**Comment by InterstellarRobo** [comment]
They are exactly that. I think I know my problem, my raspberry pi power supply is poor and is consistently under-volting. I am buying one soon and will update you once it arrives (which will be a while because I'm not paying extra for fast shipping).

**Comment by InterstellarRobo** [comment]
![image](https://user-images.githubusercontent.com/46660453/101840549-efde4d80-3b09-11eb-8727-f9e179f993d0.png)
These are my settings. I bought a new power supply and the pi is no longer under-volting but the images still aren't automatically sending. Is there anything weird you see here?

**Comment by InterstellarRobo** [comment]
I updated and it started working again. Whatever you did, thank you.
