### ISSUE TITLE
Bot goes offline every 30 hours or so.

### ISSUE THREAD

**Issue by groteboem** [cameroncros/OctoPrint-DiscordRemote#171]
**Describe the bug**
The bot goes offline every 30 hours or so. When I disable 'presence' and re-enable it again its online again. When its offline it still sends status updates but doesnt respond to commands.

[**Logs**](https://we.tl/t-YlFS6HPsHh)

**Comment by cameroncros** [comment]
Sorry for the silence, try release 2.67, it hopefully will either fix the problem, or give better debug logs.

**Comment by groteboem** [comment]
[Logs.zip](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/6136524/Logs.zip)

Its up to date. I dont know if this came with the new update or not, but now the bot doesn't want to go online anymore, even if I disable and re-enable presence again, or restart the pi. I attatched the logs. Thanks!

**Comment by cameroncros** [comment]
Looks like the presence connection is not working correctly, unfortunately, I did not write that code, so I will have to investigate why that is broken. Probably an incorrect assumption somewhere.
