### ISSUE TITLE
Upload Files (Suggestion)

### ISSUE THREAD

**Issue by Dragonking3x** [cameroncros/OctoPrint-DiscordRemote#172]
I currently have two 3d Printers. One is at home and the other one at my Fathers place. I don't want OctoPrint to be open to the internet except with Discord. Sending him emails is connected with luck. If I don't call him, and tell him that I sent him a file, we will not find it in his email. Giving him a USB stick every time could be close to donating him a USB stick.

A Command like "-sendfile {filepath}" would be a nice solution to this. You would only have to send the command and include the file in the message.

I thought about searching other plugins for that, but if I have this one installed, it would be better for me if this plugin has that function.

**Comment by cameroncros** [comment]
If you drop a file into the discord channel that octoprint is listening on,
it will be uploaded to octoprint. I think this is what you want?

**Comment by Dragonking3x** [comment]
Exactly

**Comment by cameroncros** [comment]
Well, I have good news, that's exactly what happens right now! But, this is
the second question about this feature, so it probably should be documented
better.
