### ISSUE TITLE
Fix Precision in Rich Presence status progress percentage to 2 decimal places

### ISSUE THREAD

**Issue by eScribMac** [cameroncros/OctoPrint-DiscordRemote#176]
**Is your feature request related to a problem? Please describe.**
The rich presence status progress percentage shows 8 decimal places, which is too many

**Describe the solution you'd like**
2 decimal places

**Describe alternatives you've considered**
More detailed control over presence messages

**Comment by cameroncros** [comment]
Yup, good idea, I will try fix it when I get a chance.
