### ISSUE TITLE
3rd party plugin trigger?

### ISSUE THREAD

**Issue by Fabrizio3** [cameroncros/OctoPrint-DiscordRemote#177]
there's a plugin that can send a command when the bed is at a certain temp, it would be nice if it could trigger a discordremote notification just like the status button on top, saying "Hey, this plugin said the bed is at 30c, come remove the part!", would be pretty useful
ive seen some requests for something similar around btw

**Comment by cameroncros** [comment]
You would have to speak to that plugins developer, but this is already
possible, as there is an API for sending a message via this plugin:

https://github.com/cameroncros/OctoPrint-DiscordRemote#api
