### ISSUE TITLE
PSU control seems to conflict with DiscordRemote

### ISSUE THREAD

**Issue by Forsyth-Creations** [cameroncros/OctoPrint-DiscordRemote#195]
Hello all! Ran into a weird issue today. I've just finished designing a control board for my PSU, and it auto-powers on using the "PSU-Control" OctoPrint plugin. All well and good there. However, the Discord Bot stays inactive after the PSU is powered on. Does the Discord bot only start when the server is started, and when the printer is connected?

If so, I'd love to have this fixed. It's the last issue I'm encountering with my printer (apart from bed leveling that is haha).

**Comment by cameroncros** [comment]
They shouldn't conflict, if anything, they should work together, did you solve your problem?
