### ISSUE TITLE
Buttons!

### ISSUE THREAD

**Issue by DigiVore-Programing** [cameroncros/OctoPrint-DiscordRemote#197]
**Is your feature request related to a problem? Please describe.**
No, but it's something useful.

**Describe the solution you'd like**
Discord has added buttons to the UI, and discord.py has it now. Buttons would simply the bot

**Describe alternatives**
Reaction controls and such

**Comment by cameroncros** [comment]
I still haven't completed discord.py support, but maybe once that is done it could be looked at. I am not particularly keen to work on this though, but I will accept any contributions.

**Comment by DigiVore-Programing** [comment]
If you would like, me and a friend could help you switch to Discord.JS,
which is better in many ways, and works better. However you do need to
install Javascript I think...

**Comment by cameroncros** [comment]
Discord.js is not gonna work, OctoPrint is python, so plugins need to be
python. Only reason I am using my own hand-rolled discord client instead of
discord.py is because of Octoprint not supporting python 3. If you have any
experience with discord.py, I'll happily accept PRs.

**Comment by DigiVore-Programing** [comment]
Another idea, being able to move the extruder before every snapshot (like octolapse)

I'm gonna close this issue, since you've got the idea, and I might PR it.

**Comment by cameroncros** [comment]
Thats a pretty interesting idea, but may not be terribly easy, as far as I know, octolapse modifies the gcode before its sent, so that might be as easy for this? It might be possible though, but I will leave that to you.
