### ISSUE TITLE
geting the ip of the net

### ISSUE THREAD

**Issue by deanyarongit** [cameroncros/OctoPrint-DiscordRemote#20]
hey i was wondering if there is an option to get the ip of the net from the discord channel.

**Comment by cameroncros** [comment]
There isn't currently, but certainly a possible feature. Depends what IP your after, if you want our local network IP, should be easy. If you want the internet IP, might be harder?

**Comment by cameroncros** [comment]
I added the IP address to /status. It will try to guess the IP address, but it will only be the local network IP.

**Comment by deanyarongit** [comment]
hey tnx was hoping for the outside ip  not local

**Comment by cameroncros** [comment]
Hmmmm, no idea how to do that, will have a think about it, but I don't know if it's possible without an outside service

**Comment by cameroncros** [comment]
Added ipgetter so that the external IP address as well as the local. Will be in next release.
