### ISSUE TITLE
Updated to OctoPrint 1.7 stable. got this :

### ISSUE THREAD

**Issue by SgtKiLLx** [cameroncros/OctoPrint-DiscordRemote#202]
octoprint-discordremote 2.70.0 requires websocket-client==0.57, but you have websocket-client 0.59.0 which is incompatible

**Comment by jneilliii** [comment]
Any version of websocket-client version newer than 0.59 is python3 only. I suppose OctoPrint upgraded to the latest stable version supported by both python2 and python3 with the latest update which is 0.59.0 and @cameroncros just needs to update the requirements.txt file to the newer version. If that is the case, you could verify by copying/pasting this URL into Plugin Manager > Get More > ...from URL and clicking Install.

```
https://github.com/jneilliii/OctoPrint-DiscordRemote/archive/refs/heads/master.zip
```

**Comment by cameroncros** [comment]
The requests version is very sensitive, and different versions break in weird ways.

If you are interested, the discordlib branch in my repo has a partially working discord.py implementation. It is very rough around the edges and doesnt work perfectly yet, (Double messages, no snapshots, etc) but it does work.

I will get a download url shortly.

**Comment by cameroncros** [comment]
Download url is:

```
https://github.com/cameroncros/OctoPrint-DiscordRemote/archive/refs/heads/discordlib.zip
```

You'll need python 3.

Thanks @jneilliii for trying to fix it, I appreciate the effort.

**Comment by cameroncros** [comment]
Sorry, I misspoke, it's the websocket-client, not requests that is flakey. I will correct my other comment.

**Comment by SgtKiLLx** [comment]
> Sorry, I misspoke, it's the websocket-client, not requests that is flakey. I will correct my other comment.

Any clue as to what needs to be fixed? I kinda miss using this plugin .

**Comment by cameroncros** [comment]
Best option, upgrade to python3 on your octoprint, and install `https://github.com/cameroncros/OctoPrint-DiscordRemote/archive/refs/heads/discordlib.zip` 

Next best option would be to manually downgrade websocket-client to version 0.57: `pip install websocket-client==0.57`. This might break other features, so ideally avoid it.
