### ISSUE TITLE
WHY WAS MY ISSUE CLOSED

### ISSUE THREAD

**Issue by cameroncros** [cameroncros/OctoPrint-DiscordRemote#203]
If you are reading this, it is likely I just closed your issue ticket with no resolution.

Many if not all of the issues I was drowning under were related to the broken discord implementation. With v3.0.0 of discordremote, those issues should all be fixed. Because I have limited time and energy, I have decided to close all previous issues, to remove the clutter. If after upgrading to v3.0.0 your issue still persists, please re-open the ticket (Or create a new one).

**Comment by vfrdirk** [comment]
FWIW, I think I had an old issue in here but I installed the recent update and it seems to be fixed. Thanks for the updates!
