### ISSUE TITLE
"Permission denied" response to all commands I send through Discord

### ISSUE THREAD

**Issue by twistedpixel** [cameroncros/OctoPrint-DiscordRemote#204]
**Describe the bug**
"Permission denied" response to all commands I send in Discord. This seems to only happen if using my user ID (the long string of numbers obtained by clicking the ... button on my profile settings page) in the User field of the "Access settings" section of OctoPrint's DiscordRemote settings. When I use "*" it works fine. I know the ID is correct as I've triple checked it and also it worked fine before the 3.0 update. Is it looking for a different ID now in 3.0? I read your instructions and they still seem to indicate that is the correct ID to use.

Octoprint is on the latest version (1.7)

Any idea what's going on?

**Logs**
\# This is all there seems to be in the Discord plugin log
2021-10-19 13:19:58,327 ERROR Failed with: list assignment index out of range
2021-10-19 13:19:58,535 ERROR Failed with: list assignment index out of range
2021-10-19 13:19:58,758 ERROR Failed with: list assignment index out of range
2021-10-19 13:24:04,956 INFO Settings have saved. Send a test message...
2021-10-19 13:24:04,967 INFO Received event: test
2021-10-19 13:24:08,629 INFO Sending msgs
2021-10-19 13:24:27,151 INFO Settings have saved. Send a test message...
2021-10-19 13:24:27,158 INFO Received event: test
2021-10-19 13:24:30,792 INFO Sending msgs

**Screenshots**
In case it isn't clear, here's what I'm inputting. Also I only actually use rule 1 - I only filled rule 2 for this screenshot to show you the difference of what I'm inputting to rule 1's Users and Commands box.
<img width="923" alt="Screen Shot 2021-10-19 at 13 29 01" src="https://user-images.githubusercontent.com/1885273/137910476-ef536da5-6b28-41c6-86d3-dffea7a5a224.png">

**Comment by McStebb** [comment]
Hello.  Sorry for the necro. I am now having this precise issue with version v5.6.0.
I am able to receive messages from the server but cannot send commands.

Adding * / * works, just as @twistedpixel did above. Using the channel ID doesn't work.

![image](https://github.com/cameroncros/OctoPrint-DiscordRemote/assets/46116575/e431a1e3-2e66-4dee-b0c7-cef35e9d43be)

**Comment by cameroncros** [comment]
Do you mean user ID doesn't work? Make sure you are getting the correct user ID, which comes from right clicking your name and clicking copy-id (I am on mobile so not 100% sure how to do this on desktop). Should be something like: 371XXXXXXXXXXXX520. I'll test on my server anyway

**Comment by McStebb** [comment]
You're right, sorry.  I misspoke.  I did mean user ID.
I can put in the 4XXX... user id of the public bot but it won't let me issue commands, however giving all commands to all users works.

**Comment by cameroncros** [comment]
No, sorry for the confusion, it should be the user id of the user you want
to be able to send commands, so you own user ID.

**Comment by McStebb** [comment]
OMG...... That makes sense. I can't believe I missed that.
Thank you. It's working now.
