### ISSUE TITLE
Redundant messages form single command.

### ISSUE THREAD

**Issue by scooterg2004** [cameroncros/OctoPrint-DiscordRemote#205]
Issues started after v3.0

When using commands in discord, bot replies with multiple redundant messages. for example when using !status the bot will post 2 status messages. when !snapshot is used it posts 4 snapshots.

I have uninstalled and cleaned data, rebooted octopi server, kicked the bot, deleted old bot from dev portal and started all over and the issue persists.

**Comment by cameroncros** [comment]
I assume closed because you found a fix? I haven't seen this before.
