### ISSUE TITLE
/timelapse not returning list of files

### ISSUE THREAD

**Issue by sonjamichelle** [cameroncros/OctoPrint-DiscordRemote#206]
When I issue the /timelapse command this is all it gives me:

```
Sonja K2SMT — Today at 6:02 AM
/timelapse

Ender3-Max-Bot
BOT
 — Today at 6:02 AM
Creality Ender 3 Max
Files and Details
Download with /gettimelapse {filename}
Today at 6:02 AM
```

The /files command works as expected so I have the base url set correctly. Also have allow_scripts set to true as well.

When I issue the /gettimelapse command I get this:

```
Sonja K2SMT — Today at 6:06 AM
/gettimelapse Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4

Ender3-Max-Bot
BOT
 — Today at 6:06 AM
Uploaded Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4 in 21 parts
Today at 6:06 AM
[6:06 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.001
5.00 MB
[6:06 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.002
5.00 MB
[6:06 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.003
5.00 MB
[6:06 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.004
5.00 MB
[6:06 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.005
5.00 MB
[6:07 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.006
5.00 MB
[6:07 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.007
5.00 MB
[6:07 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.008
5.00 MB
[6:07 AM]

Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.009
5.00 MB
```

It just continues on and on. I had to restart the octoprint instance.

When I click the provided download link I get this:

`Wheel_scaled_115__CE3MAX_PLA_04mm_PLASQSLOWZ_2H_38M_20210721204635.mp4.zip.021`

Even after renaming It shows as corrupted.

**Comment by cameroncros** [comment]
The file upload spam is due to discords file limits. You needs to download all the files, and then open the first one in 7zip or similar. It will open up properly then. Don't rename them.

I can confirm the timelapse list is broken, I will try fix it shortly

**Comment by sonjamichelle** [comment]
Ooook, I got it. I didn't realize it was splitting the archive into parts. Makes sense now.  Thank you!!

OH, BTW, kudos on getting the presence bug fixed!!!!
