### ISSUE TITLE
Was working, now not.

### ISSUE THREAD

**Issue by SgtKiLLx** [cameroncros/OctoPrint-DiscordRemote#207]
So I seen that there are some fixes going on.. I installed discordremote for both Octo instances, I have each bot in its own seperate channel. At first, it worked, now its not. Not sure why.. both bots are "online"

I cleaned up the data, kicked the bot.. set everything back up, I get the initial "settings are correct" screen shot, operational image in the channel. but as soon as I type a command in, nothing happens.

**Comment by cameroncros** [comment]
Do you have any logs you can dig out for me?

**Comment by SgtKiLLx** [comment]
> 
> 
> Do you have any logs you can dig out for me?

nope. if you can give me your discord again, I can reinstall it all, and show you.

**Comment by cameroncros** [comment]
https://discord.gg/qqkFemUP
