### ISSUE TITLE
Status not showing Snapshot

### ISSUE THREAD

**Issue by MilitaryPawn** [cameroncros/OctoPrint-DiscordRemote#210]
It used to be the case that if I ran /status I would get all of the printer info along with a snapshot from the camera.  It may have changed a while ago but now with the latest version when I run /status I only get the info and I have to separately run /snapshot to get a picture.  Is it possible to change this behavior in a config or something so that I can restore that previous behavior?

Thanks!
Chris

**Comment by cameroncros** [comment]
This is probably a bug, I will look into it

**Comment by cameroncros** [comment]
Will be in the next release
