### ISSUE TITLE
Printer or Profile ID

### ISSUE THREAD

**Issue by WWE-Corey** [cameroncros/OctoPrint-DiscordRemote#224]
**Is your feature request related to a problem? Please describe.**
I run 3 instances of Octoprint with DiscordRemote tied to a single Discord Bot. It is not clear which printer is posting activity.

**Describe the solution you'd like**
Include a method of naming the printer or use the Profile Name when sending updates to Discord.

**Describe alternatives you've considered**
I see the IP/Hostname option but it is not sending any data (blank) and those are not very clear anyway.

**Additional context**
n/a

**Comment by cameroncros** [comment]
There are a few options that may suit.

You could create another 3 discord bots, and then name them as you please.
You could also set the title for the octoprint server, and it should be used as the author field, which goes at the top of the embed:
![image](https://user-images.githubusercontent.com/1438383/185729836-fb46276d-edc9-46cb-a86f-987beeb0f37b.png)
![image](https://user-images.githubusercontent.com/1438383/185729883-084bb93d-8dcc-4d8a-b1b6-ff0657e00e54.png)

The IP/hostname stuff is exclusively for the /status command.

**Comment by WWE-Corey** [comment]
Thank you - I assumed as much for the other options and went the route of 3 individual Bots. Thank you.

**Comment by cameroncros** [comment]
Cool. Sounds like you are all sorted then, I'll close this ticket
