### ISSUE TITLE
DiscordRemote - not responding on commands through Discord

### ISSUE THREAD

**Issue by nabzster** [cameroncros/OctoPrint-DiscordRemote#228]
Hi,

I have an Ender 3 Pro with Octoprint and I decided to use the DiscordRemote plugin. I installed everything and I'm getting the bot to type messages in Discord but I can only run the "/" commands in octoprint. If I run it on Octoprint, the bot would respond in discord. If I use my user in Discord and type for example, "/status" it will not respond at all. I've tried setting the user permission with my ID and "*" same with the commands to "*" but have had no luck.

I'm not sure if the BASE URL is correct for my setup. I'm just using the https://[local-ip]/api/plugin/discordremote

The DiscordRemote is always green on octoprint.

Not sure what I should do next, thank you so much for the help.

**Comment by samuellogan** [comment]
Have you tried setting rule #1 as follows:
![15D8E962-2C88-4136-817A-EE5ECE550353](https://user-images.githubusercontent.com/42814104/192135298-66817315-e1df-4781-9b58-99668e49ffa3.jpeg)
I didn't make use of the base url and left it blank. Sorry i can't be of any more help lol

**Comment by gopgop9000** [comment]
Having the same issue, it detects the message when I use a command, but does nothing with it (from the Debug level logs). No reply or anything, and no further information on the logs.
![image](https://user-images.githubusercontent.com/22566921/193481044-aa9a03ee-6e72-4c46-b073-066778bf3e3a.png)

**Comment by gopgop9000** [comment]
Just looked at closed issues (I really wish that was the default) and it was fixed by the steps in https://github.com/cameroncros/OctoPrint-DiscordRemote/issues/226.

**Comment by nabzster** [comment]
Holy crap. It works! Thank you so much.

**Comment by cameroncros** [comment]
Sounds like I need to update the doco if this is tripping up lots of people. Will try do that asap

**Comment by DrToxic** [comment]
Not sure if still an issue or not. but check gateway intents.

This is how I got DiscordRemote to work.

![image](https://user-images.githubusercontent.com/41945324/210318049-ca3b658a-5dab-4c28-a265-886aa27f3efd.png)

**Comment by Ryan526** [comment]
> Not sure if still an issue or not. but check gateway intents.

Thank you this fixed my issue!
