### ISSUE TITLE
Failed to Find File

### ISSUE THREAD

**Issue by nick-elzer** [cameroncros/OctoPrint-DiscordRemote#230]
Hi! I have successfully installed the bot and have the server up and running. All commands are working fantastically so far, except when trying to access the files on the printer. When I try the /print {filename} or /getfile {filename}, it states that it failed to find the file. I have used /files to ensure that the file I am referring to is in fact on there and that it sees it, and I have tried typing it everyway possible. Any suggestions?

**Comment by cameroncros** [comment]
What was the solution if you don't mind me asking?

**Comment by nick-elzer** [comment]
I was sleepy brained and apparently "typing it everyway possible" did not include without the brackets lol. Tried it again this morning and it was the first thought, now everything works beautifully. Great plugin!
