### ISSUE TITLE
Bot Permissions Issue 

### ISSUE THREAD

**Issue by luccassa** [cameroncros/OctoPrint-DiscordRemote#242]
I can only get the bot to greet, no commands can be issued from both discord or the octoprint client. I followed the issue #226 and made sure an asterix was present on commands and users. I also made sure the bot had all three settings enabled and it had full admin privilege. The bot connects, sends wake-up text, snapshot of my printer, then is unresponsive.

![image](https://user-images.githubusercontent.com/19500448/233865777-9471e966-edf1-4ac5-a979-0bd74de286e0.png)
![image](https://user-images.githubusercontent.com/19500448/233865805-69d359f9-4191-4f28-82e7-b475686453c9.png)

**Comment by Austnikl** [comment]
Hey are you able to send a command through Octopi i seem to have a similar issue. 

Are you able to send a status command from octopi?

**Comment by luccassa** [comment]
No commands are accepted either from the Octoprint UI, or discord.

**Comment by Austnikl** [comment]
i am having the same issue im able to get this msg and nothing else . 

![image](https://user-images.githubusercontent.com/22736657/233871720-5b551193-04fb-4bc1-995f-033f9d03bb33.png)

here are my logs 
[plugin_discordremote.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/11305237/plugin_discordremote.log)
[plugin_pluginmanager_console.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/11305238/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/11305239/octoprint.log)

**Comment by Austnikl** [comment]
i have enabled the privileged gateways 

![image](https://user-images.githubusercontent.com/22736657/234057546-01e1b2fe-d9a0-4b4a-b26a-a5fc9558af8f.png)

**Comment by luccassa** [comment]
> I have enabled the privileged gateways. and still can't get any msg sent across.

Same here

**Comment by cameroncros** [comment]
@Austnikl Do you have Octorant and DiscordRemote installed at the same time? AFAIK they shouldnt conflict, but I have never tested it.

**Comment by cameroncros** [comment]
Are you both using v4.1 of DiscordRemote?

**Comment by Austnikl** [comment]
i am however i was having this issue before installing Octorant. and i am running Discordremote 4.1

**Comment by cameroncros** [comment]
Try uninstalling v4.X and installing the latest v3.X version:

https://github.com/cameroncros/OctoPrint-DiscordRemote/archive/refs/tags/v3.11.0.zip

Some people have had issues with v4.x, so it may be worth trying the older version until I fix things.

**Comment by Austnikl** [comment]
i will give it a go and let you know.

**Comment by Austnikl** [comment]
that version you sent me works I can send commands in discord.

**Comment by luccassa** [comment]
Worked for me as well. I will say that I tried 4.2 and the commands were
functioning from the UI side only. However, it was extremely slow
compared to the functional 3.11 build. Thanks for the help and awesome
plugin. Good luck!

**Comment by cameroncros** [comment]
Sounds like your both happy now, I will close this off. Create a new issue if you have any other problems.
