### ISSUE TITLE
V5.0 - Bot not working

### ISSUE THREAD

**Issue by cameroncros** [cameroncros/OctoPrint-DiscordRemote#253]
v5.0 has a completely new method of connecting to discord.

Your old bot from v2-4 will not be used anymore, and you will need to either:

- Setup discordshim: https://github.com/cameroncros/discordshim_rs

Or 

- Add the official discordshim bot to your server: https://discord.com/oauth2/authorize?client_id=433252064324354048&permissions=11264&scope=bot

Troubleshooting:

- Run: `python -m octoprint_discordremote.connectiontest [CHANNEL_ID]` on your octoprint machine. See if you can send messages.
  - If you get a prompt, you should be able to send messages, and also receive messages.
 
- Remove and re-add the bot to your discord server. Check permissions.

- If still not working, DM "Cameron C" on the octoprint discord.

**Comment by CompuGenius** [comment]
@cameroncros I added the official discordshim bot to my server and filled in the channel ID, yet no test message or commands are working.

**Comment by thenixhex311** [comment]
> @cameroncros I added the official discordshim bot to my server and filled in the channel ID, yet no test message or commands are working.

same here

**Comment by cameroncros** [comment]
Does the discordshim bot have permission to post to the channel you have chosen?

**Comment by CompuGenius** [comment]
> Does the discordshim bot have permission to post (and read messages) to the channel you have chosen?

Yes, of course

**Comment by cameroncros** [comment]
I have restarted the discordbot, it was in an odd state, see if that helps. If not, can you contact me on discord to debug this further?

I am Cameron C on the octoprint discord.

**Comment by CompuGenius** [comment]
> If not, can you contact me on discord to debug this further?
> 
> I am Cameron C on the octoprint discord.

Sent you a DM

**Comment by thenixhex311** [comment]
I personally now had the "wake up ...what are we going to print today" appear, and now see "playing to 13 instances" under the bot on the userlist, but can't seem to get commands to work, going to see if it's something I messed up

**Comment by MrFrickinFixit** [comment]
Same problem as well. I get a response from the bot after reinstalling the plugin, but nothing following that. No command responses or webcam snapshots.

**Comment by cameroncros** [comment]
I think I have found the bug responsible for all your issues, and I will push a new version v5.1 shortly

**Comment by CompuGenius** [comment]
Can confirm that the bot seems to work now!

**Comment by MrFrickinFixit** [comment]
Can confirm v5.4 is working on all three of my Pi's.

**Comment by MrFrickinFixit** [comment]
Ok, maybe not. Wake up messages work.  / commands work. Snapshots work. Start of print reports not working. Same for all three Pi's.

**Comment by EvilGremlin** [comment]
now bot is ofline and don't respond to commands in channel, but manual commands from octo UI work

**Comment by cameroncros** [comment]
There is some more bugs I need to fix, and my hosting provider has had some
outages overnight.

**Comment by cameroncros** [comment]
Unless I hear otherwise, at this point everything seems stable and working? Please get in touch if you still have problems.

**Comment by MrFrickinFixit** [comment]
Looks to be functioning correctly. Command and printer progress messages reporting as expected. Thank you for your efforts.

**Comment by dshokouhi** [comment]
does the new bot respond to `/help` or anything? I cant get it to work after adding the bot and granting proper permission

**Comment by cameroncros** [comment]
It should be responding, it appears to be up and working for me at least. Have you added the new bot to your discord and given it permission to read from the channel you want to send and recieve messages on?

**Comment by dshokouhi** [comment]
> Have you added the new bot to your discord and given it permission to read from the channel you want to send and recieve messages on?

yup just double checked and those permissions are granted in teh channel the bot is added to



> @dshokouhi - Actually, it seems that it had stopped working for me, I have restarted the bot

still not responding to `/help` for me :(

**Comment by cameroncros** [comment]
@dshokouhi Can you DM me on discord, I can try assist you. I am Cameron C on the Octoprint discord.

**Comment by cameroncros** [comment]
Resolution seems to be removing and re-adding the bot to the discord server. Seems that permissions were incorrect somehow. (I recently got the bot verified, which may have impacted the permissions?
