### ISSUE TITLE
Be able to send mentions into the channel

### ISSUE THREAD

**Issue by Prototype7813** [cameroncros/OctoPrint-DiscordRemote#254]
**Is your feature request related to a problem? Please describe.**
Is it possible to make the @mentions work? I went to put my 3d printer thread in mute and received important parts only.

**Describe the solution you'd like**
Make the mentions work, if possible

**Comment by cameroncros** [comment]
I haven't looked at this lately, but I believe that bots are intentionally
not allowed to @mention in embeds.

As things appear to be finally stable, I can look into @mentions again, but
I can't promise anything.

**Comment by Prototype7813** [comment]
Thank you!

Le mer. 16 août 2023, 6 h 33 a.m., Cameron ***@***.***> a
écrit :

**Comment by cameroncros** [comment]
Okay, I think mentions should now work. You'll need to add `<@433252064324354048>` to the message you want to send the mention. Replace the numbers with the user id of the person you want to mention. Let me know if there are any issues.

**Comment by Prototype7813** [comment]
Hi Cameroncros! 

Is there something I need to do on my side to make it work? I just tried it and I have the same issue. 

Thanks for your fast response! 

![2023-08-20 12_09_54-#3dprinter_status _ Home Network - Discord](https://github.com/cameroncros/OctoPrint-DiscordRemote/assets/42559053/f3bc1627-3871-4b5b-bf70-461d180afd39)

**Comment by Prototype7813** [comment]
Hi ! 

It's perfect ! It's working . The only thing is the mention appear in and out of the text area. But it's a minor thing . 

![image](https://github.com/cameroncros/OctoPrint-DiscordRemote/assets/42559053/fc8cc495-ee78-469a-9862-80e343c80d55)

**Comment by cameroncros** [comment]
Yup, that's intentional, unfortunately you can't have mentions inside the
embed. Annoyingly, it doesn't seem to do the substitution properly in the
title of the embed, so it looks a bit ugly.

**Comment by Prototype7813** [comment]
At this point , it's working so I will not complain ! 

We can close this but maybe for improvement, it will be possible to add a field into the discord settings and add a checkbox for the message you want to add the mentions to and like that , it will hide the placeholder into the message.

Again thanks for the fast developpement
