### ISSUE TITLE
[ feature request ]  ip hide

### ISSUE THREAD

**Issue by jon012198** [cameroncros/OctoPrint-DiscordRemote#27]
a box to say show ext ip or don't show it and same for local ip

**Comment by tdub415** [comment]
You can edit the text it displays on events in the configuration (at least I'm fairly sure you can) and remove the IP address part.

**Comment by jon012198** [comment]
you can but not on /status

**Comment by cameroncros** [comment]
Okay, this should be easy enough.

**Comment by cameroncros** [comment]
v2.12 has hideable IP addresses.
