### ISSUE TITLE
Feautre request: add a minimum update interval configuration option.

### ISSUE THREAD

**Issue by nmistry** [cameroncros/OctoPrint-DiscordRemote#28]
Frequent 10% intermediate updates are not always helpful when printing smaller jobs.    Proposing the addition of a "minimum update interval" configuration option.   The system would then update on the X% if the interval between the current and last update were > the "minimum update interval".     The start and end notification should be exempt from this configuration.   

Having too many notifications potentially has the implication of users simply tuning out the update.    By making this a configurable parameter, users are able to select the interval that works best for them.   

Personally I use this reminder to periodically check on my prints. 

Thanks.

**Comment by cameroncros** [comment]
Done. See v2.13.
