### ISSUE TITLE
Printing at 100% message

### ISSUE THREAD

**Issue by tdub415** [cameroncros/OctoPrint-DiscordRemote#33]
Is there a way to exclude the 100% message, but still get the incremental messages?  I like having the "Print complete" message, but when getting status updates every X% as well as having the complete message, I get double pinged upon completion.

**Comment by cameroncros** [comment]
Okay, sounds reasonable. How about, if the done event is enabled, don't send the 100% event?

**Comment by tdub415** [comment]
Perfect, exactly what i'd like to see.  I personally much prefer the "print finished" message because it lists the total time, instead of the 100% complete progress message :)
