### ISSUE TITLE
Capability for custom commands

### ISSUE THREAD

**Issue by OctopusProteins** [cameroncros/OctoPrint-DiscordRemote#34]
This would be an excellent feature to add. For example, one could add a custom command "/light" and use their RPI to toggle a lamp. I would be willing to help add this, I just need to know what this would entail with regards to how the plugin is set up. Maybe the command could trigger a python script, etc.

**Comment by cameroncros** [comment]
Have a look at https://github.com/cameroncros/OctoPrint-DiscordRemote/blob/master/octoprint_discordremote/command_plugins/psu_control.py

That is my example custom command plugin style. If you already have a working plugin that can turn on and off the lamp, you may be able to copy that file and produce a working /light command. 

You would also need to add your plugin in here:
https://github.com/cameroncros/OctoPrint-DiscordRemote/blob/master/octoprint_discordremote/command_plugins/__init__.py

Is this what you are looking for? Or do you have something else in mind? I am very open to rearchitecting the plugin system to make it more useful.

**Comment by OctopusProteins** [comment]
This might be able to work. I'll take a look at those files. One question, how do you use the plugins? Is there a step to activate them? For example, doing "/poweron" just brings up the help dialog right now.

**Comment by cameroncros** [comment]
All the plugins are enabled at startup. The setup() function is used to check if the PSUControl octoprint plugin is installed, and if it is, it registers the /poweron commands. 

You should do something similar, so the /light command only gets registered if the pi has a light attached.

**Comment by OctopusProteins** [comment]
I've decided to make use of the Octoprint-Enclosure plugin to control my GPIO pins. I'm writing a plugin that will interface with the API to enable and disable GPIO pins from Discord. Would this be something you'd be interested in merging after its done? I'll send a PR after its finished.

**Comment by cameroncros** [comment]
That is definitely something I would be keen to merge in. And re-using the existing Octoprint-Enclosure plugin was almost exactly what I intended with the plugin system I added. If you need any help, I'm more than happy to look over any code.

**Comment by OctopusProteins** [comment]
@cameroncros #35

**Comment by OctopusProteins** [comment]
@cameroncros #35

**Comment by cameroncros** [comment]
@OctopusProteins I added some feedback to your #35 PR. The nicer embed layout is the only one I really care about, the command naming is a bit more personal preference tbh

**Comment by OctopusProteins** [comment]
I don't see the feedback. Did you post it as a comment on the PR?

**Comment by cameroncros** [comment]
Yes, on the PR, dunno how it shows up for your end though?

**Comment by OctopusProteins** [comment]
Hmmm... I don't see anything. Could you maybe try reposting or copy it here? Thanks.

**Comment by cameroncros** [comment]
I had only two points:
* Maybe /encOn is not the nicest naming, but, I am not sure what a better name would be. 
* The status output is not the nicest, you should use the full embed builder, and add a field for each switch?

Also, there seems to be a bit more functionality of the EnclosurePlugin that could be exposed (scripts), but that could be done later i guess

**Comment by OctopusProteins** [comment]
Thanks for the feedback. I can fix the embeds definitely. There are more functions in the enclosure plugin, but the Enclosure plugin API is not very robust. Basic GPIO is the only fleshed-out feature so far. What would you suggest for the command naming? I was going to use "/on", "/off" and maybe "/gpiostatus" but I thought they would be too generic.

**Comment by cameroncros** [comment]
perhaps "/inputon 1", "/inputstatus" as the command structure? No other commands use camelcase either, so might fit in better

**Comment by OctopusProteins** [comment]
I'll use "/outputon" and "/outputstatus" since they are more of outputs than inputs. Those sound much better. I'll add more commits! Thanks.

**Comment by cameroncros** [comment]
derp, of course they are outputs! Its obviously late here. Functionality wise, I am happy with your changes, so i'll merge and release them tomorrow.

**Comment by OctopusProteins** [comment]
Awesome, thanks! By tomorrow, I may have added some more changes to add in those other enhancements and fix the / before filename issue if thats ok with you?

**Comment by cameroncros** [comment]
sounds good!

**Comment by cameroncros** [comment]
"if len(params) > 2" <- you had it right the first time didnt you? Should be len(params) > 1?

**Comment by OctopusProteins** [comment]
params also contains the command itself.
params[0] = /outputon
params[1] = 1
So the length is two for a properly formatted command.

**Comment by cameroncros** [comment]
Yup, just worked that out, your right.

**Comment by cameroncros** [comment]
I have cleaned up the minor changes, and merged the PR, I will release it tonight or tomorrow.

**Comment by OctopusProteins** [comment]
@cameroncros Sure nothing big, maybe a small note somewhere?
