### ISSUE TITLE
Support to change command prefix

### ISSUE THREAD

**Issue by OctopusProteins** [cameroncros/OctoPrint-DiscordRemote#37]
Here's another enhancement idea:
Let the user change what character they want in front of the command. So they could change to
.help, or even ./help
 
@cameroncros If you want this setting, I have the code already and I'll make a PR.

**Comment by cameroncros** [comment]
Yep, saw your code already, sounds like a great idea. Someone else wanted something similar, so definitely open the PR.

**Comment by cameroncros** [comment]
Merged and accepted.
