### ISSUE TITLE
Feature suggestion: Turn of Bot

### ISSUE THREAD

**Issue by Joroks** [cameroncros/OctoPrint-DiscordRemote#45]
Could you add the possibility to turn of the bot with a simple button. so it doesn't spam you when you are for exampe at Home were you don,t really need it. It would be good if you can toggle this even mid print

**Comment by cameroncros** [comment]
Interesting idea, like a /mute and /unmute command? Should definitely be possible, I'll try get it implemented over the next week or so.

**Comment by cameroncros** [comment]
I'd prefer to expose it as a command, as the setting area is already quite full. After I implement it, if your still not happy, I can always add it in as a separate web interface control somewhere

**Comment by cameroncros** [comment]
Done. Released in v2.24. If you have any further issues or requests, please create a new ticket :)
