### ISSUE TITLE
Add estimate time to 📢 Printing is at {progress}%

### ISSUE THREAD

**Issue by rhys100** [cameroncros/OctoPrint-DiscordRemote#48]
It would be great if there was a command for "how long its currently been printing" and "eta till print is finished"

Then this "📢 Printing is at {progress}%"

could be changed to

📢 Printing is at {progress}%
So far i've been printing for 2 hours.
Current ETA is 1 hour 65 minutes.

etc

**Comment by rhys100** [comment]
yea thats good but when u have 8 printers running they all reply lol.

So would be better to get that info from some dedcated commands like {eta} or {timeprinted}

**Comment by cameroncros** [comment]
I'll look into it, but to be fair, I did warn against putting all your printers on one channel :P

**Comment by rhys100** [comment]
thanks for implementing that! Is there a way to do multiple lines?

Currently, mine says 
📢 Printing is at {progress}% I've been printing for {timespent} and I have {timeremaining} to go!

But splitting it up like this would be better

📢 Printing is at {progress}%
 I've been printing for {timespent}
 I have {timeremaining} to go!

**Comment by cameroncros** [comment]
Turns out that this has been doable already, as long as you manually edit the config files. I have changed the UI so that you can input multi-line status messages
