### ISSUE TITLE
Missing Dependency "ipgetter"

### ISSUE THREAD

**Issue by ghost** [cameroncros/OctoPrint-DiscordRemote#49]
It would appear that `ipgetter` is gone from the the pip repository and installations are now failing -- or is this just me?

https://pypi.org/search/?q=ipgetter

There really should be a better way of doing this than pulling this package in. A simple GET request to http://checkip.amazonaws.com/ will return this without all these extraneous dependencies.

**Comment by cameroncros** [comment]
Hmm, that is a shame. The reason I went with the library was to avoid depending on a particular site existing or being up. ipgetter used a bunch of different services, so was potentially more reliable.
I'll switch to checking that amazon address.

**Comment by cameroncros** [comment]
Im keeping ipgetter, and just moving the script into the plugin itself. I prefer the redundancy that ipgetter offers over the amazon solution, but if there are issues in the future, I may replace it.
