### ISSUE TITLE
Long tooltip breaks TouchUI navigation

### ISSUE THREAD

**Issue by blazze11** [cameroncros/OctoPrint-DiscordRemote#52]
The long tooltip of the navbar icon breaks the navigation on touchscreen devices with the touchui plugin.
Maybe change it to show only DiscordRemote.
![screenshot_chrome_dev_20181103-114434](https://user-images.githubusercontent.com/8845639/47951265-9c7a9800-df5e-11e8-96ca-726c4ee8e365.png)

**Comment by cameroncros** [comment]
Hmm, interesting. This kinda feels like a bug in TouchUI, rather than this plugin. Have you asked them whether that dev is willing to look into it? If they don't care/don't want to fix it, I am more than happy to shorten the message

**Comment by blazze11** [comment]
I will report it to the touchui dev. Thanks for your response.

**Comment by cameroncros** [comment]
Tracked by https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/253

**Comment by cameroncros** [comment]
@blazze11 is this something that still bothers you?

**Comment by blazze11** [comment]
Yes

**Comment by cameroncros** [comment]
Righto, I'll shorten the message for now. Seems the other project is not too interested in fixing it.
