### ISSUE TITLE
ipgetter address blacklisted

### ISSUE THREAD

**Issue by Seelge** [cameroncros/OctoPrint-DiscordRemote#53]
Some of the sites used in ipgetter.py seem to be on a blacklist causing my router to send me emails and notifications every few minutes. I have disabled "Show External IP" but this does not seem to have any effect.

![image](https://user-images.githubusercontent.com/2706323/50002000-f67b6e00-ff9e-11e8-8e5a-91411a105dd2.png)

**Comment by cameroncros** [comment]
I'll look into this. I think it should be easy to fix. Just curious, and this has nothing to do with the bug, but what router do you have that sends notifications? Seems like a cool feature?

**Comment by Seelge** [comment]
Thank you for the fast fix!

My router is a Synology RT1900ac.
