### ISSUE TITLE
/status commands not working

### ISSUE THREAD

**Issue by Joshua-Roe** [cameroncros/OctoPrint-DiscordRemote#54]
running octoprint on puppy linux 14.04 thar. Everything appears to be set up correctly both on octoprint and discord text channel, all commands work apart from /status, tried from discord and from octoprint page.

**Comment by cameroncros** [comment]
Hi Joshua, Can you please get the logs from your octoprint instance and attach them to this ticket? I dont have enough information to debug your problem.

**Comment by Joshua-Roe** [comment]
@cameroncros which logs do you mean as I cannon find a log file for discordremote

**Comment by cameroncros** [comment]
@Joshua-Roe Discord remote logs get lumped into the main octoprint logs, can you get me those? Give them a quick read over yourself to ensure there is no private information though.

**Comment by Joshua-Roe** [comment]
[octoprint.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/2695267/octoprint.log)

Hi here is the main octoprint log file,
I tested the command before saving and notice the error at end of file.

**Comment by cameroncros** [comment]
Very interesting. Give me a few days to analyse your issue and I will try get it fixed. In the short term, you could try going to the settings for DiscordRemote, and disabling the external ip address lookup. Something there is buggy for you.

**Comment by cameroncros** [comment]
@Joshua-Roe I am not certain, but it seems that your python ssl module is broken. You may need to reinstall it. Python ssl should be built into the system, so you might need to use your linux package manager. 

Side note: Puppy Linux is up to 7, and 14.04 is an Ubuntu version number. Which OS are you using? Also, Ubuntu 14.04 was release 4 years ago, you may want to get to update your version?

**Comment by cameroncros** [comment]
@Joshua-Roe Im gonna assume this is closed. If you still have issues, please re-open this ticket and supply some logs. I can also remotely debug if you are comfortable with that.
