### ISSUE TITLE
Long prints generating multiple progress notifications when a timeout is set

### ISSUE THREAD

**Issue by tdub415** [cameroncros/OctoPrint-DiscordRemote#62]
I have noticed that when I have a long print that will stay at a progress percentage for long time that if the bot is set to only notify every X seconds, it will notify multiple times for the same progress checkpoint if it is still at the same checkpoint percentage it already reported.

Example: I had a 68 hour print.  I have the bot set to only notify if at least 10 minutes have passed since the previous notification (so i'm not spammed with them on really short prints).  Given how long the print was, it usually sat at each percentage for 30+ minutes, so at each 10%, i got three to four notifications spaced approximately 10 minutes apart, as long as the progress was still at the same X0% status.

**Comment by cameroncros** [comment]
That is interesting, sounds like Octoprint is notifying the plugin multiple times for a single percentage? As always, logs would help, but this might be an easy fix

**Comment by tdub415** [comment]
I'll pull the log when I get off work; My best guess was the bot was polling for the progress when the timeout was over, and since it saw a X0% progress, it posted it again.

**Comment by cameroncros** [comment]
Thats not how it works, progress events are pushed to the bot by OctoPrint. I'll just add a check that the current X% is not the same as the previous one.

**Comment by cameroncros** [comment]
@tdub415 Are you using the periodic reporting function, or the percentage reporting function with the minimum timeout? If it is the first, I'd argue that the plugin is working as designed, but I can make it optional to hide duplicates if you want?

**Comment by tdub415** [comment]
Percentage every 10% with 600 second timeout

**Comment by tdub415** [comment]
Whoops, replied via email and not here.  I have it set to notify every 10% with a 600s (10 minute) timeout

**Comment by cameroncros** [comment]
Test v2.33 and let me know if it fixes the issue.
