### ISSUE TITLE
/connect reports failure but actually succeeds

### ISSUE THREAD

**Issue by goscicki** [cameroncros/OctoPrint-DiscordRemote#69]
Perhaps it is inconsequential, but every time I send a /connect command it always returns with "Failed to connect" but it is immediately followed by "Your printer is operational". Everything works fine so this would obviously be very low priority.

**Comment by cameroncros** [comment]
https://github.com/cameroncros/OctoPrint-DiscordRemote/blob/master/octoprint_discordremote/command.py#L258
The method for checking if connect is successful or not relys on a timeout. It could do with a refactor anyway, so I will see if there is a better way to detect the connection success.

**Comment by goscicki** [comment]
This works perfectly now.

**Comment by cameroncros** [comment]
Fixed and released.
