### ISSUE TITLE
Bot setup instructions unclear

### ISSUE THREAD

**Issue by jon012198** [cameroncros/OctoPrint-DiscordRemote#7]
it dose not post or listen to the channel i did give it permissions

**Comment by jon012198** [comment]
i found out i did not have dev mode on

**Comment by cameroncros** [comment]
The instructions to set it up could be more clear. I will try write something up at some point. Will keep this open to track the issue

**Comment by jon012198** [comment]
i did get it to work https://puu.sh/AAq7v/e3907a2ea1.png

**Comment by jon012198** [comment]
i used this https://github.com/Chikachi/DiscordIntegration/wiki/How-to-get-a-token-and-channel-ID-for-Discord and this https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by jon012198** [comment]
how do you make a bot stay online

**Comment by cameroncros** [comment]
Fixed doco here: 70a872a0c0205487963df8c17a1c0fed67a746da

As for the bot staying online, not sure. I may have missed something when i created the discord bot (AFAIK there are no python 2 discord bots apart from this one). I will look into it more. See #10 as it is probably related.

**Comment by jon012198** [comment]
i did not program my bot that is why i need to do that

**Comment by jon012198** [comment]
Bot was there then it went offline
