### ISSUE TITLE
/print files from SD card

### ISSUE THREAD

**Issue by goscicki** [cameroncros/OctoPrint-DiscordRemote#71]
Is there any way to /list and /print files stored on the SD card?

**Comment by cameroncros** [comment]
Afaik, it was already possible? I'll have to do some testing though.

**Comment by goscicki** [comment]
Oh. None of the files I have on my SD card show in /list and they won't print with /print. Maybe it has to do with the fact that my OctoPrint is running in Windows instead of on a pi.

**Comment by cameroncros** [comment]
Probably not the windows thing, i might not have it correctly setup. I don't print from the SD card, so its basically untested
