### ISSUE TITLE
permission denied after update

### ISSUE THREAD

**Issue by andypoo79** [cameroncros/OctoPrint-DiscordRemote#74]
Hi
i am unable to issue any commands to the printer after todays update. I have the * in the acxess box but still "permission denied", no change if i add my user ID it still responds "permission denied". is their any way to roll back?

many thanks

**Comment by andypoo79** [comment]
please ignore my above post, i didnt realise i now have to give each user every command they can use. its a pain but i understand security and all

**Comment by cameroncros** [comment]
@andypoo79 you should be able to put * in both boxes, and every user will have access to every command, does that not work for you?

**Comment by Slayforfun** [comment]
I just discovered i have the same problem but I cant seem to find where I would input the asterisk for this, at least on on the plugin window of octoprint.

**Comment by cameroncros** [comment]
![image](https://user-images.githubusercontent.com/1438383/56888522-8259e680-6ab7-11e9-9d8c-f52a4313cd08.png)
You need to put * in both sides, and that allows all users to access all commands. If you want to lock it down, you can put a specific set of users, or a specific set of commands, or a combination of both.
If you need more information, please let me know.

**Comment by Slayforfun** [comment]
Well the biggest problem, I think, is that I cant find that menu/header. The plugin configurations still look exactly the same as the way it did before I updated

**Comment by cameroncros** [comment]
Ctrl-F5 to refresh the page?

**Comment by Slayforfun** [comment]
yeah i just checked it on my laptop and there it did show, I feel stupid haha. Chrome hadnt refreshed the page as I opened the tab after a reboot of my pc. Thought it would be handled by my pi but shouldve been aware of this. Thanks for the patience, help and all your hard work :)

**Comment by andypoo79** [comment]
> @andypoo79 you should be able to put * in both boxes, and every user will have access to every command, does that not work for you?

Hi yes this does work for me thanks
