### ISSUE TITLE
Prefixes are not validated

### ISSUE THREAD

**Issue by cameroncros** [cameroncros/OctoPrint-DiscordRemote#78]
@gcurtis79 has reported that the prefixes are not validated.

**Comment by gcurtis79** [comment]
Forgive my bad GitHub etiquette. My forked patch worked, but I have a feeling there is a better method than my hack-job.

**Comment by cameroncros** [comment]
@gcurtis79 Not a problem at all, all contributions are welcome.

**Comment by cameroncros** [comment]
released
