### ISSUE TITLE
Send Commands

### ISSUE THREAD

**Issue by welshmnky** [cameroncros/OctoPrint-DiscordRemote#8]
Hi, can you please list the commands that can be sent to the bot through Discord? I've used the Telegram bot so I know to try /files and /print, but beyond that I'm lost. Thanks!

**Comment by jon012198** [comment]
there is a /help one you can use that will tell you

**Comment by welshmnky** [comment]
It would be helpful to see that in the instructions. Could you also add commands to see the status of the print (show Z height, % complete, and time remaining), as well as a command to toggle pausing the printer. Very helpful when swapping filament mid-print!

**Comment by cameroncros** [comment]
Currently working on a status command, but havent made much progress. Pause and Unpause should be easy enough.

**Comment by cameroncros** [comment]
/help command is documented now: 586bd0fd8e1c592d1b88fc79b5f5e19899fc9ce7

**Comment by cameroncros** [comment]
Status, pause and resume are completed: #11
