### ISSUE TITLE
I can't get mentions to work

### ISSUE THREAD

**Issue by Skullmonkey** [cameroncros/OctoPrint-DiscordRemote#83]
I have tried multiple formats to get mentions to work. I have tried @name and @name#(####) and the bot just prints them in plain text.

Here are screenshots of the settings I have tried: https://imgur.com/a/R2qzNIM

Am I missing something?

**Comment by cameroncros** [comment]
i have no idea if that is the right way to do mentions. I will do some research and work it out

**Comment by Skullmonkey** [comment]
If it isn't, you may want to update your documentation: https://github.com/cameroncros/OctoPrint-DiscordRemote#message-format

**Comment by cameroncros** [comment]
That documentation is mostly from the older https://github.com/bchanudet/OctoPrint-Octorant#message-format project that this is forked from. I will work out what needs to be done and get back to you.

**Comment by cameroncros** [comment]
According to: https://discordjs.guide/popular-topics/embeds.html#resending-embeds
"Mentions in embeds will not trigger a notification".

@Skullmonkey If you desperately need @mentions to work, please let me know and I will think of a way forward.
