### ISSUE TITLE
Can't access files/timelapses from outside of home network

### ISSUE THREAD

**Issue by Sunlis** [cameroncros/OctoPrint-DiscordRemote#84]
It seems there used to be `/getfile` and `/gettimelapse` commands, which were removed in favour of download links in `/files` and `/timelapse` respectively.
My biggest usecase for DiscordRemote is interfacing with my printer when I'm not on my home network, since I don't want to open my octoprint instance up external requests.

I believe Discord has an 8mb upload limit, which would block some of the larger files out there. But would it be possible to add a command to attempt a file upload, and fail if the file is too large?

**Comment by cameroncros** [comment]
This is certainly possible, however, most GCODE files and timelapses I have seen are well over the 8mb limit, which is why I gave up on that method.
I could look into sending the files in chunks, but I can't promise anything.
[ ] See if file uploading in chunks will work.

**Comment by Sunlis** [comment]
Well I can't speak for everyone, but I use Octolapse to keep my timelapses short - guess it keeps them small too. The largest one I have right now is 6.8MB.

**Comment by cameroncros** [comment]
https://stackoverflow.com/a/51296157 <- chunked zip, will work with 7z apparently

**Comment by cameroncros** [comment]
haven't done timelapses yet, but added file upload for gcode. Will add timelapses soon

**Comment by cameroncros** [comment]
@Sunlis I have added the /getfile and /gettimelapse functionality, if you are interested, you could test it by installing the feature/file_upload branch. Otherwise I will merge and release it in a few days

**Comment by cameroncros** [comment]
@Sunlis the changes have been merged and released. If there are any issues, please create a ticket.
