### ISSUE TITLE
/listsystemcommands doesn't work

### ISSUE THREAD

**Issue by EvilGremlin** [cameroncros/OctoPrint-DiscordRemote#86]
It just doesn't respond to that command. Also, how do i run my custom commands from config.yaml ? It says syntax should be source/command, but what is source for my commands?

**Comment by cameroncros** [comment]
It is working for me:

**Comment by cameroncros** [comment]
https://github.com/foosel/OctoPrint/wiki/Cookbook:-System-Commands <- this is a good resource for how to add system commands. There is also a plugin to assist: https://plugins.octoprint.org/plugins/systemcommandeditor/

**Comment by EvilGremlin** [comment]
Yeah, my config looks exactly like that. Doesn't work with bot. BTW, what distro you use? Mine is ARMBIAN 5.75 stable Ubuntu 18.04.2 LTS 4.19.20-sunxi. Maybe that's the case?

**Comment by cameroncros** [comment]
It's not distro related, it was a bug in the parsing of the commands. Install the system commands plugins, and try again.

**Comment by EvilGremlin** [comment]
Thanks man, will try this evening.

**Comment by EvilGremlin** [comment]
Okay, i got something new in log now:
2019-07-19 21:25:06,453 - websocket - ERROR - error from callback <bound method Discord.on_message of <octoprint_discordremote.discord.Discord instance at 0xa9b7bb98>>: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
Well, i changed names to latin and finally got commands list, but ASCII? WTF? It's 2019, UTF-8 is default standard everywhere now.

**Comment by cameroncros** [comment]
Probably mine, Gina is German, I suspect she has proper utf-8 support. I will check that later and push a fix if it's my end.

**Comment by cameroncros** [comment]
So, definitely my end. Or python 2's end, but I believe it is fixed. If there are any issues, let me know.

**Comment by EvilGremlin** [comment]
Yeah, now it's perfect. I guess it's more python's heritage than bug.

**Comment by cameroncros** [comment]
Yeah, I learnt something as well. At least in python 3 you can use str, as it is unicode, but until octoprint jumps up to python 3, it's out of my hands :(
