### ISSUE TITLE
Version number not matching.

### ISSUE THREAD

**Issue by tdub415** [cameroncros/OctoPrint-DiscordRemote#87]
I think the version number didn't get updated correctly again. I'm being prompted to update despite just updating.

**Comment by cameroncros** [comment]
Damn, I'll try fix it shortly

**Comment by cameroncros** [comment]
Should be fixed i think

**Comment by tdub415** [comment]
Looks like the version number didn't update again, 2.46 is downloading and installing labeled as 2.45

**Comment by cameroncros** [comment]
This is getting frustrating...

**Comment by cameroncros** [comment]
Should be fixed. Gonna leave this ticket open as a reminder to do something about it to stop this happening.
