### ISSUE TITLE
Remove "Extruder Temp (chamber)" 

### ISSUE THREAD

**Issue by andrelec1** [cameroncros/OctoPrint-DiscordRemote#93]
I have a Prusa MK3 and dont have this value...

when i /status i see : 
![image](https://user-images.githubusercontent.com/3273204/63138078-4486bc80-bfd9-11e9-87b8-9f14f487d6a7.png)

Juste provide a checkbox like external/local ip for showing this value :)

**Comment by cameroncros** [comment]
If you create a PR, i would be happy to merge that. But, I am not particularly concerned about that, given it still functions.

**Comment by andrelec1** [comment]
Sorry, i'm not python dev :/ 

I think this is in fault :
https://github.com/cameroncros/OctoPrint-DiscordRemote/blob/cdb91cc0597cc1da0872d2c28fc38c6c5841d861/octoprint_discordremote/command.py#L312-L315

but when i go throuth http://octoprint/api/printer
the json look like :
```json
{
  "state": {
    "flags": {
      "cancelling": false, 
      "closedOrError": false, 
      "error": false, 
      "finishing": false, 
      "operational": true, 
      "paused": false, 
      "pausing": false, 
      "printing": true, 
      "ready": false, 
      "resuming": false, 
      "sdReady": false
    }, 
    "text": "Printing"
  }, 
  "temperature": {
    "bed": {
      "actual": 50.9, 
      "offset": 0, 
      "target": 50.0
    }, 
    "tool0": {
      "actual": 215.8, 
      "offset": 0, 
      "target": 215.0
    }
  }
}
```

so didn't understand where the "chamber" key come from ...
i try to search in all project ... didn't found anything :/
