### ISSUE TITLE
Add layer progess ...

### ISSUE THREAD

**Issue by andrelec1** [cameroncros/OctoPrint-DiscordRemote#94]
In /status can you add the current layer / total layers  ...

**Comment by cameroncros** [comment]
Maybe. I vaguely recall attempting this, and finding that there is no way for a plugin to get the current layer. I may look into this in the future, but if you submit a PR, i would be happy to merge it.

**Comment by andrelec1** [comment]
I'm not python dev, but actualy a use this plugin :
https://plugins.octoprint.org/plugins/layerdisplay/

and you can get json info throught; http://octoprint/api/plugin/layerdisplay
```json
{
  "layerString": "57 / 688"
}
```

**Comment by cameroncros** [comment]
I'm hesitant to rely on other plugins for core functionality. Im not going to close this ticket, so if someone comes along, they can implement it, but I will likely not do it.

**Comment by andrelec1** [comment]
I didn't understand why the layer progression isn't add natively in Octoprint ...

**Comment by cameroncros** [comment]
Me neither to be honest. I guess it is hard to work it out on vase-mode prints?

**Comment by andrelec1** [comment]
Vase-mode is juste a print with lot of layer ...
All plugin that track the layer progression analyse the gcode for counting `G1 Zxxx` instruction
