### ISSUE TITLE
Support Multicam 

### ISSUE THREAD

**Issue by andrelec1** [cameroncros/OctoPrint-DiscordRemote#95]
I use this plugin 
https://plugins.octoprint.org/plugins/multicam/ 

That permit to add more than one cam on the printer ...

Can you add something for selecting wich webcam is used for sending snapshot
( or sending all webcam )  ??

**Comment by cameroncros** [comment]
If you submit a PR i would be happy to merge it. But, this feels like a lot of work to do, and test.

**Comment by Zinc-OS** [comment]
I might try this for fun.
