### ISSUE TITLE
Put /help in permission system

### ISSUE THREAD

**Issue by andrelec1** [cameroncros/OctoPrint-DiscordRemote#98]
I have some stupid guy's in my discord that spam /help , and try every command -_-" ....
Can you just put the /help in the restriction systeme like other command ?

**Comment by cameroncros** [comment]
My rationale for leaving help outside the permissions system is that I wanted it to be always available.
Moving it into the permissions system does somewhat compromise that, but I am happy to do it. Note that if it becomes a problem later down the line, i might revert it.

Also, I strongly suggest you use discords permissions to block users from posting to your discord channel. If I made a mistake in the permissions system, they could very easily damage your printer or start a fire. Discords permission system is far better tested than the poor one I put together.

**Comment by andrelec1** [comment]
you absolutely right...
