### ISSUE TITLE
/status command seems to be not working

### ISSUE THREAD

**Issue by tdub415** [cameroncros/OctoPrint-DiscordRemote#99]
I have noticed recently that /status doesn't seem to be working.  Other commands like /snapshot are still working for me.

**Comment by cameroncros** [comment]
Can you find any log messages that seem relevant?

**Comment by tdub415** [comment]
2019-08-21 23:44:47,112 - websocket - ERROR - error from callback <bound method Discord.on_message of <octoprint_discordremote.discord.Discord instance at 0x73672738>>: object of type 'float' has no len()

**Comment by tdub415** [comment]
it looks like this may have been fixed in v2.46, which i was almost positive i had updated to, but it looks like I'm still on 2.45

**Comment by cameroncros** [comment]
Yeah, sounds like the issue fixed in 2.46, so I think i will close this. Feel free to reopen it if you have further issues.

**Comment by tdub415** [comment]
Yea, 2.46 fixed it, but looks like 2.46 is installing labeled as 2.45.  I
updated the comments of
https://github.com/cameroncros/OctoPrint-DiscordRemote/issues/87 since it's
doing it again.
